add main service
Kolobok37/java-explore-with-me pull request #2
Opened 2024-01-22 19:27 UTC by Kolobok37

2024-01-24 21:21 UTC, Yang-Pi requested changes

2024-01-24 21:21 UTC, Yang-Pi commented on ewm-service/Dockerfile
> +CMD sleep 15
А ты для чего добавил? какую проблему пытаешься решить?

2024-01-24 21:21 UTC, Yang-Pi commented on ewm-service/src/main/java/com/ewmservice/service/EventService.java
> +        List<EventFullDto> eventFullDto = eventStorage.getMyEvents(userId, Paging.paging(from, size)).stream()
Хм, в этом методе получается такая ситуация:
- для пользователя запрашиваются все его эвенты
- далее для каждого эвента делается запрос в сервис статистики для получения просмотров

те фактически если на странице будет 100 эвентов, то будет 100 запросов и соотвественно 100 запросов к бд на стороне сервиса статистики - это дорого)

Причем обрати внимание, что сервис статистики ведь поддерживает несколько uri, поэтому лучше этот метод обновить
- получить все эвенты
- и затем для всех эвентов получить просмотры
- и далее уже кодом их смэтчить

тогда выходит, что вместо 100 будет 1 запрос

2024-01-24 21:21 UTC, Yang-Pi commented on ewm-service/src/main/java/com/ewmservice/service/EventService.java
> +        if (StateEventDto.PUBLISH_EVENT.equals(eventInDto.getStateAction())
Весь этот набор if можно вынести в соответсвующий методы вроде
- isPublishedEvent(eventInDto)
- isRejectedEvent(eventDto)

так будет проще читать код метода updateEventByAdmin

2024-01-24 21:21 UTC, Yang-Pi commented on ewm-service/src/main/java/com/ewmservice/service/EventService.java
> +        if (rangeStart != null) {
Идеальный момент для применения тернарного оператора
`LocalDateTime startTime = rangeStart != null ? LocalDateTime.parse(rangeStart, formatter) : LocalDateTime.of(1400, 1, 1, 0, 0);`

2024-01-24 21:21 UTC, Yang-Pi commented on ewm-service/src/main/java/com/ewmservice/service/EventService.java
> +        List<AppDto> obj1 = eventClient.getStats(uris);
И кто такой этот obj1?)

2024-01-24 21:21 UTC, Yang-Pi commented on ewm-service/src/main/java/com/ewmservice/service/EventService.java
Общий комментарий - следуй принципу Inversion of Control, когда есть интерфейс и классы его определяющие. Актуально для **всех** сервисов

2024-01-27 16:19 UTC, Kolobok37 commented on ewm-service/src/main/java/com/ewmservice/service/EventService.java
> +        if (StateEventDto.PUBLISH_EVENT.equals(eventInDto.getStateAction())
Так как много вариантов StateEventDto, пришлось сделать 3 метода, читаемость улучшилась, но не сильно)

2024-01-27 16:33 UTC, Kolobok37 commented on ewm-service/Dockerfile
> +CMD sleep 15
Пытался сделать так чтоб сервисы не запускались быстрее БД, сделал это черех doxcker compose

2024-01-28 16:50 UTC, Yang-Pi approved these changes

2024-01-28 22:53 UTC, merged